language: php
php:
  - hhvm
  - "5.5"

install:
   - composer selfupdate
   - composer --profile --prefer-source --no-interaction install

# Acceptance tests
before_script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then sudo travis/nginx/nginx.sh; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then sudo pear install PHP_CodeSniffer; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then sudo phpenv rehash; fi"

script:
  - phpcs src
  - cd app
  - phpunit

after_script:


notifications:
  email: "master.zion@gmail.com"
