language: php
php:
  - hhvm

install:
   - composer selfupdate
   - composer --profile --prefer-source --no-interaction install

# Acceptance tests
before_script:
  - echo $TRAVIS_PHP_VERSION
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] ; chmod +x travis/nginx/nginx.sh
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] ; travis/nginx/nginx.sh
  - pear install PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs src
  - cd app
  - phpunit

after_script:


notifications:
  email: "master.zion@gmail.com"
