language: php
php:
  - hhvm
  - 5.5

install:
   - composer selfupdate
   - composer --profile --prefer-source --no-interaction install

# Acceptance tests
before_script:
  - apt-get install php-codesniffer
  - phpenv rehash
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then sudo travis/nginx/nginx.sh; fi

script:
  - phpcs src
  - cd app
  - phpunit

after_script:


notifications:
  email: "master.zion@gmail.com"
