language: php
php:
  - hhvm
  - 5.5

install:
   - composer selfupdate
   - composer --profile --prefer-source --no-interaction install

# Acceptance tests
before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then sudo travis/nginx/nginx.sh; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pear install pear install pear/PHP_CodeSniffer; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pear uninstall phpunit/PHPUnit; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pear uninstall phpunit/PHPUnit_Selenium; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pear install phpunit/PHPUnit; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pear install phpunit/PHPUnit_Selenium; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv rehash; fi

script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpcs src; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/behat/behat/bin/behat --config travis/behat.yml; fi
  - cd app
  - phpunit

after_script:


notifications:
  email: "master.zion@gmail.com"
