language: php
php:
  - hhvm
  - "5.5"

install:
   - composer selfupdate
   - composer --profile --prefer-source --no-interaction install

# Acceptance tests
before_script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then  travis/nginx/nginx.sh; fi"
  - pear install PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs src
  - cd app
  - phpunit

after_script:


notifications:
  email: "master.zion@gmail.com"
